version: 2.0
jobs: 
  build: 
    docker: 
      image: "mcr.microsoft.com/dotnet/core/sdk:2.2"
      steps: 
        - checkout
        - 
          run: 
            command: "dotnet restore"
            name: "Restore packages"
        - 
          run: 
            command: "dotnet build"
            name: "Build App"
        - 
          run: 
            command: "dotnet run"
            name: "Run App"
